### ISSUE TITLE
Issue setting VPE parameters on ssc338q (in my case).

### ISSUE THREAD

**Issue by alkorgh** [OpenIPC/divinus#23]
Hi. 
I have: ssc338q+imx415.

In particular, the call to the fnSetChannelParam function (aka MI_VPE_SetChannelParam) does not set level3DNR as expected, but actually off it:
`cat /proc/mi_modules/mi_vpe/mi_vpe0`		
	
	ChnId  Rot  bMirr/flip  Gradient  ActEn  3DNRLevel  mhalHdrMode  miHdrMode
	    0    0(   0,    0)         0      0          0            0          0

Picture quality in this case is significantly worse than on the same majestic, where this function seems not to be used (not found by search, but it should be checked with its developers). As I understood by default 3DNRLevel == 2, if it is “do not touch”.

I see a quick (but not correct) solution to the problem at this stage by commenting the block in the i6_hal.c file: 

	324	//{
	325	//  i6_vpe_para param;
	326	//  param.hdr = I6_HDR_OFF;
	327	//  param.level3DNR = 1;
	328	//  param.mirror = 0;
	329	//  param.flip = 0;
	330	//  param.lensAdjOn = 0;
	331	//  if (ret = i6_vpe.fnSetChannelParam(_i6_vpe_chn, &param))
	332	//    return ret;
	333	//}
The noise in the image becomes significantly less, since 3DNR is working.

More correctly, ask @flyrouter where the `mi_vpe.ko` & `libmi_vpe.so` files (implementing VPE_SetChannelParam) come from on the OpenIPC firmware and why said function is not working properly. Maybe it is necessary to replace these files in the firmware?

**Comment by wberube** [comment]
Nice find! I just pushed a fix on commit 98c236bb6a3 that addresses this,

I hadn't completed the lens distortion correction structs for infinity6(b0) and infinity6e, a feature for which I intend to add support in the long term, neither had I referenced them in the VPE structs correctly.

Everything seems to work just fine on my test device now, but you can give it a check at let me know if it's not the case on yours.

**Comment by alkorgh** [comment]
Yes, it works now.
However, I would like to understand the structures in more detail.

According to the SDK on Pudding, the `MI_VPE_SetChannelParam` function takes a pointer to the `MI_VPE_ChannelPara_t` structure, which is defined like this:

	typedef struct MI_VPE_ChannelPara_s
	{
	   MI_VPE_PqParam_t      stPqParam; // only dvr use
	   MI_VPE_HDRType_e      eHDRType;
	   MI_VPE_3DNR_Level_e   e3DNRLevel;
	   MI_BOOL               bMirror;
	   MI_BOOL               bFlip;
	   MI_BOOL               bWdrEn;    //Wdr on/off not use
	   MI_BOOL               bEnLdc;
	} MI_VPE_ChannelPara_t;

It's from here:
https://wx.comake.online/doc/doc/SigmaStarDocs-SSC9381G_9351_Pudding-ULS00V040-20210913/customer/development/mi/V2/vpe.html#312-mi_vpe_channelpara_t

You use your own `i6e_vpe_para `structure for this purpose:
	
	typedef struct {
		char reserved[16];
		i6e_vpe_ldc lensAdj;
		i6_common_hdr hdr;
		// Accepts values from 0-7
		int level3DNR;
		char mirror;
		char flip;
		char reserved2;
		char lensAdjOn;
	} i6e_vpe_para;  

Where does the "extra" field with the `i6e_vpe_ldc `structure come from, and at the same time with many fields that have specific names?

As far as I understand reverse-engineering can at best only define field sizes, but not their semantic designations. 

Where do you get the correct names? What sources do you use (which SDK)?

An answer would be appreciated.

**Comment by wberube** [comment]
There are a couple of repositories referencing pudding on GitHub but none were actual enough to match the SDK components that compose the latest firmware (including the docs you shared). I can't say for sure what revision of the SDK is used as we speak, but it's greater than v040.

I knew from experience that some features were going to be backported from more recent platforms. The initialization parameters that populate the matching field in the VPE channel attributes are on par with what you can find on some tiramisu headers (https://github.com/qanthink/skyipc_runde/blob/master/soc_sdk/include/mi_ldc_datatype.h).

I figured the rest out with a good Ghidra session and an evening of trial and error.

**Comment by alkorgh** [comment]
I don't understand anything, but it's very interesting. 
Perhaps at the moment I am not skilled enough to understand decompiled code (I also looked inside using Ghidra).

I can't understand how VPE and LDC are related, but the repository you link to has a file mi_vpe_datatype.h (https://github.com/qanthink/skyipc_runde/blob/master/soc_sdk/include/mi_vpe_datatype.h), which doesn't define the structure MI_VPE_ChannelPara_t any differently than I described.

> I can't say for sure what revision of the SDK is used as we speak, but it's greater than v040.

English is not my first language, maybe I don't understand all the subtleties.
Used by whom? Why can't you say: You don't know or bound by NDA terms?

Thank you again. I apologize for the intrusiveness, but it seems that no one but you will help me to get to the truth.

**Comment by flyrouter** [comment]
@alkorgh 
You have all the same SDKs that we have, there is nothing new

**Comment by wberube** [comment]
The newer SigmaStar platforms behave somehow differently than earlier ones and the module responsibilities have their lines blurred sometimes. Tiramisu, as used in this SDK, allows configuring its LDC peripheral in a standalone manner, some others don't even have a VPE (video processing engine) but feature a SCL module (scaling engine) that's gonna handle this task instead, etc.

Once you know what to look for, you just have to dig. I tried affecting different VPE parameters till I found none of them were making a change (3DNR, mirror, flip), so I was inevitably missing a field before these ones in my parameter struct.

**Comment by alkorgh** [comment]
@flyrouter, Hi, I agree, just trying to understand, maybe I have incomplete information.
@wberube.
Yeah I did some research too, including using MI_VPE_GetChannelParam, like:
	
	char m[256]={0};
	MI_VPE_GetChannelParam(vpeChn, (MI_VPE_ChannelPara_t*)m);
 
But this did not give any results until 92 byte were set, according by the struct `i6e_vpe_para`

So I wanted to understand what the other bytes define, where it all came from and why it is like that.

I guess I'll leave you alone at this point, used it as is and move on.
Thanks.

**Comment by alkorgh** [comment]
You're absolutely right.  

As you can see from my first message, I had a question about the origin of the libmi_vpe.so(mi_vpe.ko) library on OpenIPC. It's definitely not from the original firmware and SDK. 
It is known that the use of a library is determined by its with header files.
When you pushed a commit fix that had the exact structure of i6e_vpe_ldc (with names, complex multiple nesting, and unions), I legitimately assumed you had the appropriate `.h` file, since it's unreasonable to define all that without it and then not use structure fields in code. I usually don't do things I don't directly need to do.

If it was:
 
	typedef struct {
		char reserved[16];  // only dvr use (some PqParam)
		char unknown[72];   // patch for libmi_vpe.so, looks like a structure for "Lens distortion correction"
		i6_common_hdr hdr;
		int level3DNR;
		char mirror;
		char flip;
		char reserved2;
		char lensAdjOn;
    } i6e_vpe_para;
		
Then it would also work and I would not have any further questions.

Anyway, thanks for what you're doing, it's a great help.
